# Generated by Django 3.2.7 on 2021-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of plant', max_length=150)),
                ('description', models.CharField(blank=True, help_text='General information about the plant', max_length=500)),
                ('price', models.FloatField(help_text='Price of plant')),
                ('quantity', models.IntegerField(help_text='Quantity of the plant in storage')),
                ('category', models.CharField(blank=True, help_text='Type of plant', max_length=100)),
                ('image', models.CharField(help_text='Image of plant', max_length=500)),
                ('barcode', models.CharField(help_text='Barcode of product', max_length=100)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
